### ISSUE TITLE
Would you kindly code few more functions?

### ISSUE THREAD

**Issue by bitig** [jdiii/gae_blog#2]
Hi John, I need a simple personal blog on GAE for it is free as my blog will have very low traffic.

I like to use your GAE blog, with your permission.

Would you be able to add a couple of functions, i can promise to send you gift from Amazon.com abt worth up to $50?

I need it to be able to;
- search posts title & content
- pagination of posts 
- friendly post URL, such as;  mysite.com/my-test-post.html,  mysite.com/my-another-post.html

please let me know if you would.
thank you.

**Comment by jdiii** [comment]
@bitig I added pagination yesterday and am planning to add the other two features you mentioned over the next week or so (and yes, tips appreciated 👍)

**Comment by bitig** [comment]
@jdiii thank you. :+1: 

i will keep my promise :)

**Comment by jdiii** [comment]
hey @bitig, latest commit adds a simple search page (/blog/search)

**Comment by bitig** [comment]
Hi @jdiii just now I have tested your latest changes; 
Posts url is really important to be user friendly;

Current url looks like this; 
http://localhost:8080/blog/5311740673785856/testpost/

By removing posts id, I need it look like this; 
http://localhost:8080/blog/testpost/

maybe you can add another field named 'posturl' for user to input url separately from post title?

one other thing is, search page does not search words containing /ö/.

pagination works, simple and adequate.
thanks for your help.
